2019-06-25 15:31:46,492 INFO: Microblog startup [in /home/how_r_u/Desktop/mega_book/app/__init__.py:56]
2019-06-25 17:13:35,675 INFO: Microblog startup [in /home/how_r_u/Desktop/mega_book/app/__init__.py:56]
2019-06-25 17:13:56,441 ERROR: Exception on /reset_password_request [GET] [in /home/how_r_u/.local/lib/python3.6/site-packages/flask/app.py:1780]
Traceback (most recent call last):
  File "/home/how_r_u/.local/lib/python3.6/site-packages/flask/app.py", line 2311, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/how_r_u/.local/lib/python3.6/site-packages/flask/app.py", line 1834, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/how_r_u/.local/lib/python3.6/site-packages/flask/app.py", line 1737, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/how_r_u/.local/lib/python3.6/site-packages/flask/_compat.py", line 36, in reraise
    raise value
  File "/home/how_r_u/.local/lib/python3.6/site-packages/flask/app.py", line 1832, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/how_r_u/.local/lib/python3.6/site-packages/flask/app.py", line 1818, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/how_r_u/Desktop/mega_book/app/routes.py", line 170, in reset_password_request
    return render_template("reset_password_request.html", title="Reset Password", form=form)
  File "/home/how_r_u/.local/lib/python3.6/site-packages/flask/templating.py", line 134, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/home/how_r_u/.local/lib/python3.6/site-packages/jinja2/environment.py", line 869, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/home/how_r_u/.local/lib/python3.6/site-packages/jinja2/environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/home/how_r_u/.local/lib/python3.6/site-packages/jinja2/environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "/home/how_r_u/.local/lib/python3.6/site-packages/jinja2/loaders.py", line 125, in load
    code = environment.compile(source, name, filename)
  File "/home/how_r_u/.local/lib/python3.6/site-packages/jinja2/environment.py", line 591, in compile
    self.handle_exception(exc_info, source_hint=source_hint)
  File "/home/how_r_u/.local/lib/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/how_r_u/.local/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/how_r_u/Desktop/mega_book/app/templates/reset_password_request.html", line 15, in template
    {% endblock %}
  File "/home/how_r_u/.local/lib/python3.6/site-packages/jinja2/environment.py", line 497, in _parse
    return Parser(self, source, name, encode_filename(filename)).parse()
  File "/home/how_r_u/.local/lib/python3.6/site-packages/jinja2/parser.py", line 901, in parse
    result = nodes.Template(self.subparse(), lineno=1)
  File "/home/how_r_u/.local/lib/python3.6/site-packages/jinja2/parser.py", line 883, in subparse
    rv = self.parse_statement()
  File "/home/how_r_u/.local/lib/python3.6/site-packages/jinja2/parser.py", line 144, in parse_statement
    self.fail_unknown_tag(token.value, token.lineno)
  File "/home/how_r_u/.local/lib/python3.6/site-packages/jinja2/parser.py", line 97, in fail_unknown_tag
    return self._fail_ut_eof(name, self._end_token_stack, lineno)
  File "/home/how_r_u/.local/lib/python3.6/site-packages/jinja2/parser.py", line 90, in _fail_ut_eof
    self.fail(' '.join(message), lineno)
  File "/home/how_r_u/.local/lib/python3.6/site-packages/jinja2/parser.py", line 59, in fail
    raise exc(msg, lineno, self.name, self.filename)
jinja2.exceptions.TemplateSyntaxError: Encountered unknown tag 'endblock'.
2019-06-25 17:14:52,410 INFO: Microblog startup [in /home/how_r_u/Desktop/mega_book/app/__init__.py:56]
2019-06-25 17:14:56,661 ERROR: Exception on /reset_password_request [GET] [in /home/how_r_u/.local/lib/python3.6/site-packages/flask/app.py:1780]
Traceback (most recent call last):
  File "/home/how_r_u/.local/lib/python3.6/site-packages/flask/app.py", line 2311, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/how_r_u/.local/lib/python3.6/site-packages/flask/app.py", line 1834, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/how_r_u/.local/lib/python3.6/site-packages/flask/app.py", line 1737, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/how_r_u/.local/lib/python3.6/site-packages/flask/_compat.py", line 36, in reraise
    raise value
  File "/home/how_r_u/.local/lib/python3.6/site-packages/flask/app.py", line 1832, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/how_r_u/.local/lib/python3.6/site-packages/flask/app.py", line 1818, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/how_r_u/Desktop/mega_book/app/routes.py", line 170, in reset_password_request
    return render_template("reset_password_request.html", title="Reset Password", form=form)
  File "/home/how_r_u/.local/lib/python3.6/site-packages/flask/templating.py", line 135, in render_template
    context, ctx.app)
  File "/home/how_r_u/.local/lib/python3.6/site-packages/flask/templating.py", line 117, in _render
    rv = template.render(context)
  File "/home/how_r_u/.local/lib/python3.6/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/home/how_r_u/.local/lib/python3.6/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/how_r_u/.local/lib/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/how_r_u/.local/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/how_r_u/Desktop/mega_book/app/templates/reset_password_request.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/how_r_u/Desktop/mega_book/app/templates/base.html", line 33, in top-level template code
    {% block content %}
  File "/home/how_r_u/Desktop/mega_book/app/templates/reset_password_request.html", line 6, in block "content"
    {{ form.hidden.tag() }}
  File "/home/how_r_u/.local/lib/python3.6/site-packages/jinja2/environment.py", line 430, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'app.forms.ResetPasswordRequestForm object' has no attribute 'hidden'
2019-06-25 17:15:22,928 INFO: Microblog startup [in /home/how_r_u/Desktop/mega_book/app/__init__.py:56]
2019-06-25 17:15:30,406 ERROR: Exception on /reset_password_request [POST] [in /home/how_r_u/.local/lib/python3.6/site-packages/flask/app.py:1780]
Traceback (most recent call last):
  File "/home/how_r_u/.local/lib/python3.6/site-packages/flask/app.py", line 2311, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/how_r_u/.local/lib/python3.6/site-packages/flask/app.py", line 1834, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/how_r_u/.local/lib/python3.6/site-packages/flask/app.py", line 1737, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/how_r_u/.local/lib/python3.6/site-packages/flask/_compat.py", line 36, in reraise
    raise value
  File "/home/how_r_u/.local/lib/python3.6/site-packages/flask/app.py", line 1832, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/how_r_u/.local/lib/python3.6/site-packages/flask/app.py", line 1818, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/how_r_u/Desktop/mega_book/app/routes.py", line 169, in reset_password_request
    return rediect(url_for("login"))
NameError: name 'rediect' is not defined
2019-06-25 17:15:46,815 INFO: Microblog startup [in /home/how_r_u/Desktop/mega_book/app/__init__.py:56]
2019-06-25 17:18:18,780 ERROR: Exception on /reset_password_request [POST] [in /home/how_r_u/.local/lib/python3.6/site-packages/flask/app.py:1780]
Traceback (most recent call last):
  File "/home/how_r_u/.local/lib/python3.6/site-packages/flask/app.py", line 2311, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/how_r_u/.local/lib/python3.6/site-packages/flask/app.py", line 1834, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/how_r_u/.local/lib/python3.6/site-packages/flask/app.py", line 1737, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/how_r_u/.local/lib/python3.6/site-packages/flask/_compat.py", line 36, in reraise
    raise value
  File "/home/how_r_u/.local/lib/python3.6/site-packages/flask/app.py", line 1832, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/how_r_u/.local/lib/python3.6/site-packages/flask/app.py", line 1818, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/how_r_u/Desktop/mega_book/app/routes.py", line 167, in reset_password_request
    send_password_reset_email(user)
NameError: name 'send_password_reset_email' is not defined
2019-06-25 17:19:06,315 INFO: Microblog startup [in /home/how_r_u/Desktop/mega_book/app/__init__.py:56]
