2019-06-25 17:19:07,981 ERROR: Exception on /reset_password_request [POST] [in /home/how_r_u/.local/lib/python3.6/site-packages/flask/app.py:1780]
Traceback (most recent call last):
  File "/home/how_r_u/.local/lib/python3.6/site-packages/flask/app.py", line 2311, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/how_r_u/.local/lib/python3.6/site-packages/flask/app.py", line 1834, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/how_r_u/.local/lib/python3.6/site-packages/flask/app.py", line 1737, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/how_r_u/.local/lib/python3.6/site-packages/flask/_compat.py", line 36, in reraise
    raise value
  File "/home/how_r_u/.local/lib/python3.6/site-packages/flask/app.py", line 1832, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/how_r_u/.local/lib/python3.6/site-packages/flask/app.py", line 1818, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/how_r_u/Desktop/mega_book/app/routes.py", line 167, in reset_password_request
    send_password_reset_email(user)
  File "/home/how_r_u/Desktop/mega_book/app/email.py", line 5, in send_password_reset_email
    token = user.get_reset_password_token()
  File "/home/how_r_u/Desktop/mega_book/app/models.py", line 82, in get_reset_password_token
    app.config["SECRET_KEY"], algorithm=["HS256"]).decode("utf-8")
  File "/home/how_r_u/.local/lib/python3.6/site-packages/jwt/api_jwt.py", line 65, in encode
    json_payload, key, algorithm, headers, json_encoder
  File "/home/how_r_u/.local/lib/python3.6/site-packages/jwt/api_jws.py", line 88, in encode
    if algorithm not in self._valid_algs:
TypeError: unhashable type: 'list'
2019-06-25 17:20:13,495 INFO: Microblog startup [in /home/how_r_u/Desktop/mega_book/app/__init__.py:56]
2019-06-25 17:20:16,175 ERROR: Exception on /reset_password_request [POST] [in /home/how_r_u/.local/lib/python3.6/site-packages/flask/app.py:1780]
Traceback (most recent call last):
  File "/home/how_r_u/.local/lib/python3.6/site-packages/flask/app.py", line 2311, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/how_r_u/.local/lib/python3.6/site-packages/flask/app.py", line 1834, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/how_r_u/.local/lib/python3.6/site-packages/flask/app.py", line 1737, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/how_r_u/.local/lib/python3.6/site-packages/flask/_compat.py", line 36, in reraise
    raise value
  File "/home/how_r_u/.local/lib/python3.6/site-packages/flask/app.py", line 1832, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/how_r_u/.local/lib/python3.6/site-packages/flask/app.py", line 1818, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/how_r_u/Desktop/mega_book/app/routes.py", line 167, in reset_password_request
    send_password_reset_email(user)
  File "/home/how_r_u/Desktop/mega_book/app/email.py", line 6, in send_password_reset_email
    send_email("[Microblog] Reset your password", sender=app.config["ADMINS"][0], recipients=[user.email],
NameError: name 'send_email' is not defined
2019-06-25 17:28:15,813 INFO: Microblog startup [in /home/how_r_u/Desktop/mega_book/app/__init__.py:56]
2019-06-25 17:28:46,650 INFO: Microblog startup [in /home/how_r_u/Desktop/mega_book/app/__init__.py:56]
2019-06-25 17:28:52,797 ERROR: Exception on /reset_password_request [POST] [in /home/how_r_u/.local/lib/python3.6/site-packages/flask/app.py:1780]
Traceback (most recent call last):
  File "/home/how_r_u/.local/lib/python3.6/site-packages/flask/app.py", line 2311, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/how_r_u/.local/lib/python3.6/site-packages/flask/app.py", line 1834, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/how_r_u/.local/lib/python3.6/site-packages/flask/app.py", line 1737, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/how_r_u/.local/lib/python3.6/site-packages/flask/_compat.py", line 36, in reraise
    raise value
  File "/home/how_r_u/.local/lib/python3.6/site-packages/flask/app.py", line 1832, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/how_r_u/.local/lib/python3.6/site-packages/flask/app.py", line 1818, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/how_r_u/Desktop/mega_book/app/routes.py", line 167, in reset_password_request
    send_password_reset_email(user)
  File "/home/how_r_u/Desktop/mega_book/app/email.py", line 13, in send_password_reset_email
    text_body=render_template("email/reset_password.txt", user=user, token=token),
  File "/home/how_r_u/.local/lib/python3.6/site-packages/flask/templating.py", line 135, in render_template
    context, ctx.app)
  File "/home/how_r_u/.local/lib/python3.6/site-packages/flask/templating.py", line 117, in _render
    rv = template.render(context)
  File "/home/how_r_u/.local/lib/python3.6/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/home/how_r_u/.local/lib/python3.6/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/how_r_u/.local/lib/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/how_r_u/.local/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/how_r_u/Desktop/mega_book/app/templates/email/reset_password.txt", line 4, in top-level template code
    {{url.for("reset_password", token=token, _external=True)}}
  File "/home/how_r_u/.local/lib/python3.6/site-packages/jinja2/environment.py", line 430, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'url' is undefined
2019-06-25 17:41:00,676 ERROR: Exception on /reset_password_request [POST] [in /home/how_r_u/.local/lib/python3.6/site-packages/flask/app.py:1780]
Traceback (most recent call last):
  File "/home/how_r_u/.local/lib/python3.6/site-packages/flask/app.py", line 2311, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/how_r_u/.local/lib/python3.6/site-packages/flask/app.py", line 1834, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/how_r_u/.local/lib/python3.6/site-packages/flask/app.py", line 1737, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/how_r_u/.local/lib/python3.6/site-packages/flask/_compat.py", line 36, in reraise
    raise value
  File "/home/how_r_u/.local/lib/python3.6/site-packages/flask/app.py", line 1832, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/how_r_u/.local/lib/python3.6/site-packages/flask/app.py", line 1818, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/how_r_u/Desktop/mega_book/app/routes.py", line 167, in reset_password_request
    send_password_reset_email(user)
  File "/home/how_r_u/Desktop/mega_book/app/email.py", line 13, in send_password_reset_email
    text_body=render_template("email/reset_password.txt", user=user, token=token),
  File "/home/how_r_u/.local/lib/python3.6/site-packages/flask/templating.py", line 135, in render_template
    context, ctx.app)
  File "/home/how_r_u/.local/lib/python3.6/site-packages/flask/templating.py", line 117, in _render
    rv = template.render(context)
  File "/home/how_r_u/.local/lib/python3.6/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/home/how_r_u/.local/lib/python3.6/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/how_r_u/.local/lib/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/how_r_u/.local/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/how_r_u/Desktop/mega_book/app/templates/email/reset_password.txt", line 4, in top-level template code
    {{url.for("reset_password", token=token, _external=True)}}
  File "/home/how_r_u/.local/lib/python3.6/site-packages/jinja2/environment.py", line 430, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'url' is undefined
2019-06-25 17:42:01,633 INFO: Microblog startup [in /home/how_r_u/Desktop/mega_book/app/__init__.py:56]
